FROM lunamidori5/pixelarch:topaz_cuda

RUN sudo sed -i 's/Topaz/NoteTaker/g' /etc/os-release

ENV CMAKE_ARGS="-DGGML_CUDA=on"

ARG USERNAME=midori-ai
USER $USERNAME
WORKDIR /home/$USERNAME

COPY llama_config.yaml llama_config.yaml

RUN yay -Syu --noconfirm python-llama-cpp && yay -Yccc --noconfirm

RUN uv venv --python python3.12 --seed
RUN uv pip install llama-cpp-python[server] --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu121

CMD .venv/bin/python -m llama_cpp.server --config_file llama_config.yaml