# Basic Configuration
user_token: YOURTOKEN  # User token to use for Elroy
#database_url: sqlite:///elroy.db  # Valid SQLite or Postgres URL for the database. If Postgres, the pgvector extension must be installed.
inline_tool_calls: true  # Whether to enable inline tool calls in the assistant (better for some open source models)
debug: false  # Whether to fail fast when errors occur, and emit more verbose logging
default_assistant_name: "Becca"  # Default name for the assistant

# Model Selection Configuration
chat_model: "openai/gpt-4"  # The model to use for chat completions, if not provided, inferred from env variables
chat_model_api_base: http://localhost:8000/v1  # Base URL for OpenAI compatible chat model API. Litellm will recognize vars too
chat_model_api_key: apikey  # API key for OpenAI compatible chat model API
embedding_model: "openai/text-embedding-3-small" # The model to use for text embeddings. If not provided, inferred from env variables
embedding_model_size: 1536  # The size of the embedding model
embedding_model_api_base: http://localhost:8000/v1  # Base URL for OpenAI compatible embedding model API
embedding_model_api_key: apikey  # API key for OpenAI compatible embedding model API
enable_caching: true  # Whether to enable caching for the LLM, both for embeddings and completions

# Context Management
max_assistant_loops: 4  # Maximum number of loops the assistant can run before tools are temporarily made unavailable
context_refresh_trigger_tokens: 3300  # Number of tokens that triggers a context refresh and compression of messages in the context window
context_refresh_target_tokens: 1650  # Target number of tokens after context refresh / compression, how many tokens to aim to keep in context
max_context_age_minutes: 120.0  # Maximum age in minutes to keep. Messages older than this will be dropped from context, regardless of token limits
#context_refresh_interval_minutes: 10.0  # How often in minutes to refresh system message and compress context
enable_assistant_greeting: true  # Whether to allow the assistant to send the first message
min_convo_age_for_greeting_minutes: 10.0  # Minimum age in minutes of conversation before the assistant will offer a greeting on login
#initial_context_refresh_wait_seconds: 600  # Initial wait time in seconds after login before the initial context refresh and compression

# Memory Management
memory_cluster_similarity_threshold: 0.21125  # Threshold for memory cluster similarity
memories_between_consolidation: 15  # How many memories to create before triggering a memory consolidation operation
l2_memory_relevance_distance_threshold: 1.24  # L2 distance threshold for memory relevance
max_memory_cluster_size: 5  # The maximum number of memories that can be consolidated into a single memory at once
min_memory_cluster_size: 3  # The minimum number of memories that can be consolidated into a single memory at once

# UI Configuration
show_internal_thought: false  # Show the assistant's internal thought monologue
system_message_color: "#9ACD32"  # Color for system messages
user_input_color: "#FFE377"  # Color for user input
assistant_color: "#77DFD8"  # Color for assistant output
warning_color: "yellow"  # Color for warning messages
internal_thought_color: "#708090"  # Color for internal thought messages
