{
    "host": "0.0.0.0",
    "port": 8000,
    "models": [
        {
            "model": "/models/DeepSeek-R1-Distill-Llama-8B-GGUF/DeepSeek-R1-Distill-Llama-8B-Q3_K_M.gguf",
            "model_alias": "gpt-4",
            "chat_format": "chatml",
            "n_gpu_layers": -1,
            "offload_kqv": true,
            "n_threads": 12,
            "n_batch": 512,
            "n_ctx": 12048
        },
        {
            "model": "/models/All-MiniLM-L6-v2-Embedding-GGUF/all-MiniLM-L6-v2-Q8_0.gguf",
            "model_alias": "text-embedding-3-small",
            "n_gpu_layers": -1,
            "embedding": true,
            "offload_kqv": true,
            "n_threads": 12,
            "n_batch": 512,
            "n_ctx": 12048
        }
    ]
}